variable "access_key" {}
variable "secret_key" {}
variable "region" {
default="us-east-1"
}

#############################EC2############################

variable "Terraform_webserver_instance_type" {
       type         = string
       default      = "t2.micro"
       description  = "Test Instance"
}

variable "Terraform_webserver_tag_name" {
    type = string
    default = "Terraform_webserver"
    description = "Terraform_webserver Tag name"
}

variable "ami_id" {
    type = map
    default = {
        us-east-1    = "ami-09e67e426f25ce0d7"
        us-east-2    = "ami-0b9064170e32bde34"
        us-west-1    = "ami-0a9451b714c643b38"
    }
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}



